apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: vprofile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: vprofile
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS accounts;
    USE accounts;

    CREATE TABLE IF NOT EXISTS role (
      id int(11) NOT NULL AUTO_INCREMENT,
      name varchar(45) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

    INSERT INTO role VALUES (1,'ROLE_USER'), (2,'ROLE_ADMIN');

    CREATE TABLE IF NOT EXISTS user (
      id int(11) NOT NULL AUTO_INCREMENT,
      username varchar(255) DEFAULT NULL,
      userEmail varchar(255) DEFAULT NULL,
      password varchar(255) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

    INSERT INTO user VALUES (4,'admin_vp','admin@visualpathit.com','$2a$11$DSEIKJNrgPjG.iCYUwErvOkREtC67mqzQ.ogkZbc/KOW1OPOpZfY6');

    CREATE TABLE IF NOT EXISTS user_role (
      user_id int(11) NOT NULL,
      role_id int(11) NOT NULL,
      PRIMARY KEY (user_id,role_id),
      FOREIGN KEY (user_role_roleid) REFERENCES role (id) ON DELETE CASCADE ON UPDATE CASCADE,
      FOREIGN KEY (user_role_userid) REFERENCES user (id) ON DELETE CASCADE ON UPDATE CASCADE
    );

    INSERT INTO user_role VALUES (4,1), (4,2);
---
apiVersion: v1
kind: Service
metadata:
  name: db01
  namespace: vprofile
spec:
  selector:
    app: vprofile
    tier: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: vprofile
spec:
  selector:
    matchLabels:
      app: vprofile
      tier: mysql
  serviceName: db01
  replicas: 1
  template:
    metadata:
      labels:
        app: vprofile
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin123"
            - name: MYSQL_DATABASE
              value: accounts
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin123
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: init-sql
          configMap:
            name: mysql-initdb
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
