apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYnlyYWhhIiwicGFzc3dvcmQiOiJnaHBfT3RNQTFFNk9PZXNUTUduWUYzUXBoUTlXQ2dCTURNMGhYZXNCIiwiYXV0aCI6IllubHlZV2hoT21kb2NGOVBkRTFCTVVVMlQwOWxjMVJOUjI1WlJqTlJjR2hST1ZkRFowSk5SRTB3YUZobGMwST0ifX19
kind: Secret
metadata:
  name: ghcr-secret
  namespace: vprofile
type: kubernetes.io/dockerconfigjson
